import { SideBar } from '@/components/SideBar'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Main } from '@/components/Main'
import { NavBar } from '@/components/NavBar'
import { Providers } from '@/GlobalRedux/provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Helptech-OS',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <body className={`${inter.className} bg-gray-100`}>
        <NavBar />
        <SideBar />
        <Main>
          <Providers>
            {
              children
            }
          </Providers>
        </Main>
      </body>
    </html>
  )
}
